[package]
name = "brutefoce_hack_request"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.5.35", features=["derive"]}
futures = "0.3.31"
prettytable = "0.10.0"
rayon = "1.10.0"
reqwest = "0.12.15"
tokio = { version =  "1", features=["full"] }
